export const PUBLIC_PRICING_COPY = {
  en: {
    kicker: "Pricing",
    title: "Choose the plan that helps you respond faster, book more appointments, and grow your business.",
    description:
      "We help health professionals never miss a client by automating responses, bookings, and follow-ups 24/7.",
    mostPopular: "Most popular ⭐",
    customPriceLabel: "Custom",
    whiteLabelPriceLabel: "Starting at $199/mo",
    secondaryCta: "Starting at $199/mo — or talk to us about what you need.",
    comparisonTitle: "Compare plans",
    comparisonFeatureLabel: "Feature",
    ctas: {
      free: "Try it free",
      starter: "Start automating",
      premium: "Get Premium",
      white_label: "Contact sales",
    },
    positions: {
      free: "Try it",
      starter: "Start automating",
      white_label: "Contact sales",
    },
    descriptions: {
      free: "To test the value of your AI assistant",
      starter: "To start capturing and responding to clients automatically",
      premium: "To fill your calendar and grow faster",
      white_label: "For clinics, groups, or partners that want to scale",
    },
    messages: {
      free: "Try your AI assistant in minutes.",
      starter: "Start responding to clients on WhatsApp and automate client communication.",
      premium: "Fill your calendar and understand your clients — on autopilot.",
      white_label: "Scale your operation with a fully customized AI solution.",
    },
    highlights: {
      free: ["500 messages / month", "Web chat widget", "Appointment booking"],
      starter: ["Everything in Free", "2,000 messages / month", "Active WhatsApp AI", "Appointment reminders"],
      premium: [
        "Everything in Starter",
        "5,000 messages / month",
        "Client insights",
        "Custom assistant behavior",
        "Branded chat experience",
        "Google Calendar sync",
        "Human handoff",
        "Marketing campaigns",
        "Automated follow-ups",
      ],
      white_label: [
        "Everything in Premium",
        "Unlimited messages",
        "White label",
        "Dedicated onboarding",
        "Priority support",
        "Custom configuration",
        "Multi-location setup",
      ],
    },
    comparisonRows: [
      { label: "Messages / month", values: { free: "500", starter: "2,000", premium: "5,000", white_label: "Unlimited" } },
      { label: "Web chat widget", values: { free: "✅", starter: "✅", premium: "✅", white_label: "✅" } },
      { label: "Appointment booking", values: { free: "✅", starter: "✅", premium: "✅", white_label: "✅" } },
      { label: "Active WhatsApp AI", values: { free: "❌", starter: "✅", premium: "✅", white_label: "✅" } },
      { label: "Appointment reminders", values: { free: "❌", starter: "✅", premium: "✅", white_label: "✅" } },
      { label: "Client insights", values: { free: "❌", starter: "❌", premium: "✅", white_label: "✅" } },
      { label: "Custom assistant behavior", values: { free: "❌", starter: "❌", premium: "✅", white_label: "✅" } },
      { label: "Branded chat experience", values: { free: "❌", starter: "❌", premium: "✅", white_label: "✅" } },
      { label: "Google Calendar sync", values: { free: "❌", starter: "❌", premium: "✅", white_label: "✅" } },
      { label: "Human handoff", values: { free: "❌", starter: "❌", premium: "✅", white_label: "✅" } },
      { label: "Marketing campaigns", values: { free: "❌", starter: "❌", premium: "✅", white_label: "✅" } },
      { label: "Automated follow-ups", values: { free: "❌", starter: "❌", premium: "✅", white_label: "✅" } },
      { label: "Dedicated onboarding", values: { free: "❌", starter: "❌", premium: "❌", white_label: "✅" } },
      { label: "Priority support", values: { free: "❌", starter: "❌", premium: "❌", white_label: "✅" } },
      { label: "White label", values: { free: "❌", starter: "❌", premium: "❌", white_label: "✅" } },
      { label: "Multi-location setup", values: { free: "❌", starter: "❌", premium: "❌", white_label: "✅" } },
    ],
  },
  es: {
    kicker: "Planes",
    title: "Elige el plan que te ayuda a responder más rápido, agendar más citas y crecer tu negocio.",
    description:
      "Ayudamos a profesionales de la salud a no perder clientes automatizando respuestas, citas y seguimientos 24/7.",
    mostPopular: "Más popular ⭐",
    customPriceLabel: "Personalizado",
    whiteLabelPriceLabel: "Desde $199/mes",
    secondaryCta: "Desde $199/mes o cuéntanos lo que necesitas.",
    comparisonTitle: "Compara planes",
    comparisonFeatureLabel: "Funcionalidad",
    ctas: {
      free: "Pruébalo gratis",
      starter: "Empieza a automatizar",
      premium: "Obtener Premium",
      white_label: "Hablar con ventas",
    },
    positions: {
      free: "Pruébalo",
      starter: "Empieza a automatizar",
      white_label: "Hablar con ventas",
    },
    descriptions: {
      free: "Para probar el valor de tu asistente con IA",
      starter: "Para empezar a captar y responder clientes automáticamente",
      premium: "Para llenar tu agenda y crecer más rápido",
      white_label: "Para clínicas, grupos o partners que quieren escalar",
    },
    messages: {
      free: "Prueba tu asistente con IA en minutos.",
      starter: "Empieza a responder clientes por WhatsApp y automatiza la comunicación.",
      premium: "Llena tu agenda y entiende a tus clientes en piloto automático.",
      white_label: "Escala tu operación con una solución de IA totalmente personalizada.",
    },
    highlights: {
      free: ["500 mensajes / mes", "Widget de chat web", "Agendamiento de citas"],
      starter: ["Todo lo de Free", "2,000 mensajes / mes", "IA activa por WhatsApp", "Recordatorios de citas"],
      premium: [
        "Todo lo de Starter",
        "5,000 mensajes / mes",
        "Insights de clientes",
        "Comportamiento personalizado del asistente",
        "Experiencia de chat con tu marca",
        "Sincronización con Google Calendar",
        "Transferencia a humano",
        "Campañas de marketing",
        "Seguimientos automáticos",
      ],
      white_label: [
        "Todo lo de Premium",
        "Mensajes ilimitados",
        "White label",
        "Onboarding dedicado",
        "Soporte prioritario",
        "Configuración personalizada",
        "Configuración multi-sucursal",
      ],
    },
    comparisonRows: [
      { label: "Mensajes / mes", values: { free: "500", starter: "2,000", premium: "5,000", white_label: "Ilimitados" } },
      { label: "Widget de chat web", values: { free: "✅", starter: "✅", premium: "✅", white_label: "✅" } },
      { label: "Agendamiento de citas", values: { free: "✅", starter: "✅", premium: "✅", white_label: "✅" } },
      { label: "IA activa por WhatsApp", values: { free: "❌", starter: "✅", premium: "✅", white_label: "✅" } },
      { label: "Recordatorios de citas", values: { free: "❌", starter: "✅", premium: "✅", white_label: "✅" } },
      { label: "Insights de clientes", values: { free: "❌", starter: "❌", premium: "✅", white_label: "✅" } },
      { label: "Comportamiento personalizado del asistente", values: { free: "❌", starter: "❌", premium: "✅", white_label: "✅" } },
      { label: "Experiencia de chat con tu marca", values: { free: "❌", starter: "❌", premium: "✅", white_label: "✅" } },
      { label: "Sincronización con Google Calendar", values: { free: "❌", starter: "❌", premium: "✅", white_label: "✅" } },
      { label: "Transferencia a humano", values: { free: "❌", starter: "❌", premium: "✅", white_label: "✅" } },
      { label: "Campañas de marketing", values: { free: "❌", starter: "❌", premium: "✅", white_label: "✅" } },
      { label: "Seguimientos automáticos", values: { free: "❌", starter: "❌", premium: "✅", white_label: "✅" } },
      { label: "Onboarding dedicado", values: { free: "❌", starter: "❌", premium: "❌", white_label: "✅" } },
      { label: "Soporte prioritario", values: { free: "❌", starter: "❌", premium: "❌", white_label: "✅" } },
      { label: "White label", values: { free: "❌", starter: "❌", premium: "❌", white_label: "✅" } },
      { label: "Configuración multi-sucursal", values: { free: "❌", starter: "❌", premium: "❌", white_label: "✅" } },
    ],
  },
};
